---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/local-path-storage.yaml
images:
  - name: rancher/local-path-provisioner
    newName: registry1.dso.mil/ironbank/frontiertechnology/cortex/local-path-provisioner

patches:
  - patch: |-
      - op: replace
        path: /data/helperPod.yaml
        value: |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: helper-pod
          spec:
            priorityClassName: system-node-critical
            tolerations:
              - key: node.kubernetes.io/disk-pressure
                operator: Exists
                effect: NoSchedule
            containers:
              - name: helper-pod
                image: registry1.dso.mil/ironbank/frontiertechnology/cortex/busybox:v1.37.0
                imagePullPolicy: IfNotPresent
      - op: replace
        path: /data/config.json
        value: |-
          {
            "nodePathMap":[
              {
                "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths":["/var/lib/local-path-provisioner"]
              }
            ]
          }
    target:
      kind: ConfigMap
      version: v1
      name: local-path-config
      namespace: local-path-storage
